#Use with docker-compose -f docker-compose.yml -f docker-compose.prerender.yml up

version: '3.6'

services:
  map:
    volumes:
      - ./cfg/postgresql.prerender.conf.tmpl:/etc/postgresql/current/main/postgresql.custom.conf.tmpl
      - ./scripts/render_list_geo.pl:/usr/bin/render_list_geo
    environment:
      - RENDER_THREADS=4
      - OSM2PGSQL_EXTRA_ARGS=-C 4096 --flat-nodes /nodes/flat_nodes.bin
    shm_size: 16G
