#Use with docker-compose -f docker-compose.yml -f docker-compose.import.yml up

version: '3.6'

services:
  map:
    volumes:
      - ${PWD}/cfg/postgresql.import.conf.tmpl:/etc/postgresql/current/main/postgresql.custom.conf.tmpl
    environment:
      - IMPORT_THREADS=8
      - OSM2PGSQL_EXTRA_ARGS=-C 8192 --flat-nodes /nodes/flat_nodes.bin
      - DOWNLOAD_PBF=http://download.geofabrik.de/europe/andorra-latest.osm.pbf
      - DOWNLOAD_POLY=http://download.geofabrik.de/europe/andorra.poly
    shm_size: 16G
    restart: "no"
    command: "import"
